server:
  port: ${SERVER_PORT:80}
  jetty:
    threads:
      max: ${HTTP_MAX_THREADS:100}
      max-queue-capacity: ${HTTP_MAX_QUEUE:300}

logging:
  config: "classpath:logback-spring.xml"

spring:
  application:
    name: tweet-api-service
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
    topics:
      tweet-api:
        save:
          topic: ${KAFKA_TWEET_SAVE_TOPIC:tweet.save}

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus
  server:
    port: ${MANAGEMENT_SERVER_PORT:88}

springdoc:
  swagger-ui:
    # Sort docs in alpha order
    operations-sorter: alpha
    tags-sorter: alpha
    disable-swagger-default-url: true
    supportedSubmitMethods: ${SWAGGER_OPERATIONS:"get", "post"}
  api-docs:
    enabled: ${ENABLE_SWAGGER:true}
  cache:
    disabled: true
